---
- block:
    - apt_key:
        data: "{{ lookup('file', 'docker-apt-key') }}"
        state: present

    - name: "Add repository"
      apt_repository:
        repo: '{{ docker_repo }} {{ ansible_distribution_release }} stable'
        state: present
  when: internet_available | bool

- name: "Install docker + reqs"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ docker_packages }}"
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: "Add users to the docker group"
  user:
    name:   "{{ item }}"
    groups: "{{ docker_group }}"
    append: yes
  with_items: "{{ docker_group_members }}"
  when: docker_group_members is defined

- name: "Create docker client dir"
  file:
    name: "/etc/docker"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: "Start docker service"
  service:
    name: docker
    state: restarted
    enabled: yes

- name: "Wait for docker"
  wait_for:
    path: /var/run/docker.sock
    delay: 10
